### ISSUE TITLE
Protect default collections of site from being deleted or broken in other ways.

### ISSUE THREAD

**Issue by Sebobo** [Flowpack/media-ui#245]
When an asset collection is defined as default collection for a site, it shouldn't be possible to delete it or do something that breaks that connection.

**Comment by Sebobo** [comment]
@lorenzulrich please add any idea or information you might have on the topic.

**Comment by lorenzulrich** [comment]
In a multi-site instance with site-based permissions, you will most likely use AssetCollections as an entry point for assets. The main reasons:

* You can define a default asset collection in the Site configuration that is used for uploaded assets.
* You can use privileges to restrict assets in given asset collections to certain roles.

I see some ways to ensure that the user cannot "lock themselves out" of their own files:

* We could generally prevent deleting asset collections that have still related assets. This could be discussed as a general concept, however you could still get to a state where you can't manage assets - if you don't have any assets at all and delete the collection.
* Any asset collection that is being referenced as defaltAssetCollection from a Site can never be deleted.
* Any asset collection that is referenced by a `ReadHierarchicalAssetCollectionPrivilege` cannot be deleted. However, since this is based on the title of the asset collection, it can be circumvented quite easily.
