### ISSUE TITLE
Prevent adding assets to "all" if user has only privilege to see some collections.

### ISSUE THREAD

**Issue by Sebobo** [Flowpack/media-ui#246]
### Description

Currently when a user adds an asset to the virtual "all" collection, meaning no collection, but can only see a certain set of collections, the asset is not visible to them after upload.

### Steps to Reproduce

1. Restrict role to only see one collection
2. Upload asset to "all"

#### Expected behavior

The asset goes to their first accessible collection or they cannot select "all".

#### Actual behavior

The asset disappears

**Comment by Sebobo** [comment]
@lorenzulrich do you think we should hide/disable the "All" collection or change its behaviour to match the users privileges?

**Comment by lorenzulrich** [comment]
I'm not sure if there is a "one size fits all approach" to this.

Some considerations

* When I create a new multi-site website with one asset collection per site and respective privileges, even as an admin I might not want to have the virtual "All" collection because I might add assets to places where my editors couldn't see them.
* However, when I'm changing an existing single-site website to a multi-site, I need to see "All" assets (basically such without an asset collection) so I can "move" them to the appropriate place.

Currently, I'd be in favour of having a privilege for the "All" entry point so I could leave it on for an admin if necessary, but deactivate it for editors.

**Comment by Sebobo** [comment]
One problem is also the upload mechanism. 

During upload in the module I would need to check for collections and whether uploads without collection are allowed. But in the image editor this couldn't not be prevent right now I think, or how do you handle this?

**Comment by lorenzulrich** [comment]
Are we talking about direct upload in the Image Editor?

We always disable this, since it contributes to creating a mess. However, not everyone might feel the same ;-).

As far as I know, image upload uses the default asset collection if defined. Clearly, indepentent of the solution chosen, we need some instructions on how to set this up and the default behaviour should **not** hide the "All" asset collection.
